### ISSUE TITLE
HTML and OpenXml formating

### ISSUE THREAD

**Issue by Muffon** [x97mdr/pickles#102]
---
## Here is the source, for example(look at format):

Feature: LimitFileGeneration schedule
    In order to manufacture with current (approved) limset values
    As a manufacturing
    I want to have a limit files deployed in a controlled manner

TODO: notifikace, koho? predpokladam mailem

technical notes:
this runs as a scheduled task, e.g. periodically without user intervention (tzn. "normalne" se o to nemusim starat)
generator run is a "unit of work", unless successfully completed it does not alter any limit files

pozadavek na rychlost: cca 5min pro inzenyrske vyrobky, hodiny  vyrobni vyrobky
jediny duvod pro rozdeleni je rychlost  
zacneme s jednim generatorem, az pri potizich pridat druhy generator
(ten by mel podminku na product=DESIGN, zaroven by se nezakazoval pres CF)

implementacni poznamky:
novy beh
zjistim, jaky interval approval_seq zpracovat
zjistim, jake vyrobky se zmenily
aktualizuji cache pro kazdy povoleny limitni soubor
vygeneruju vsechny limitni soubory (uz jenom vyplyvnout na disk) do nejakeho docasneho adresare
nastavim vsecm zmenan status/datum generated (je potreba?)
pak najednou nakopiruji do cile (stejne mala sance, ze to spadne)
notifikuji
upravim status behu

---
## Here is output in HTML:

In order to manufacture with current (approved) limset values As a manufacturing I want to have a limit files deployed in a controlled manner

TODO: notifikace, koho? predpokladam mailem

technical notes: this runs as a scheduled task, e.g. periodically without user intervention (tzn. "normalne" se o to nemusim starat) generator run is a "unit of work", unless successfully completed it does not alter any limit files

pozadavek na rychlost: cca 5min pro inzenyrske vyrobky, hodiny vyrobni vyrobky jediny duvod pro rozdeleni je rychlost
zacneme s jednim generatorem, az pri potizich pridat druhy generator (ten by mel podminku na product=DESIGN, zaroven by se nezakazoval pres CF)

implementacni poznamky: novy beh zjistim, jaky interval approval_seq zpracovat zjistim, jake vyrobky se zmenily aktualizuji cache pro kazdy povoleny limitni soubor vygeneruju vsechny limitni soubory (uz jenom vyplyvnout na disk) do nejakeho docasneho adresare nastavim vsecm zmenan status/datum generated (je potreba?) pak najednou nakopiruji do cile (stejne mala sance, ze to spadne) notifikuji upravim status behu

---
## Here is formating in Word

In order to manufacture with current (approved) limset values As a manufacturing I want to have a limit files deployed in a controlled manner   TODO: notifikace, koho? predpokladam mailem  technical notes: this runs as a scheduled task, e.g. periodically without user intervention (tzn. "normalne" se o to nemusim starat) generator run is a "unit of work", unless successfully completed it does not alter any limit files  pozadavek na rychlost: cca 5min pro inzenyrske vyrobky, hodiny vyrobni vyrobky jediny duvod pro rozdeleni je rychlost  zacneme s jednim generatorem, az pri potizich pridat druhy generator (ten by mel podminku na product=DESIGN, zaroven by se nezakazoval pres CF)  implementacni poznamky: novy beh zjistim, jaky interval approval_seq zpracovat zjistim, jake vyrobky se zmenily aktualizuji cache pro kazdy povoleny limitni soubor vygeneruju vsechny limitni soubory (uz jenom vyplyvnout na disk) do nejakeho docasneho adresare nastavim vsecm zmenan status/datum generated (je potreba?) pak najednou nakopiruji do cile (stejne mala sance, ze to spadne) notifikuji upravim status behu

---

---

The point is, could you have the same output format as the source?  Thank you for this project.

**Comment by x97mdr** [comment]
Moved to https://github.com/picklesdoc/pickles/issues/4
