### ISSUE TITLE
Markdown issue with list

### ISSUE THREAD

**Issue by GlutenBoy** [x97mdr/pickles#109]
Looks like list are not properly generated (only tested it in HTML).

How to reproduce:
- Create a Feature File that contains a list in markdown syntax, exemple:

Feature: SuperDuper
  In order to do a super duper thing As a super user I want the system to super duperize something
- List Item 1
- List Item 2
- List Item 3

.
.
.
'
- When pickeling this, Pickles doesn't generate a list in HTML anyway, not sure about the other formats.

**Comment by x97mdr** [comment]
Moved to the picklesdoc repo
