### ISSUE TITLE
Unit tests intermingled with specs causes Test Results File feature to break?

### ISSUE THREAD

**Issue by aaronjrich** [x97mdr/pickles#77]
I haven't exhaustively proved this exact scenario, but what I was doing was trying to incorporate mstest results (a trx file) into the output html files.   I ran all my tests, not just my specflow tests, and when I did that the console app crashed.  When I filtered my test runs to just tests in my specflow project, it worked fine.
# bug

**Comment by x97mdr** [comment]
Hi Aaron, do you have an example of this behavior that you can share?

**Comment by aaronjrich** [comment]
I believe I located this issue that I was experiencing.  See pull request (created issue #80)
