### ISSUE TITLE
Pickle-Features : Requested value xxx was not found.

### ISSUE THREAD

**Issue by Muffon** [x97mdr/pickles#94]
In version 0.4, neither docx or pdf not working with -DocumentationFormat switch.

**Comment by x97mdr** [comment]
You will want to upgrade to 0.6 to get the latest features, 0.4 is a bit old at this point.

If you want .docx output, use "-DocumentationFormat Word" as described here: https://github.com/x97mdr/pickles/wiki/ArgumentsDocumentationFormat

PDF is not a supported output mechanism at this point because you can generate PDF from either Word or DITA output.

**Comment by Muffon** [comment]
Thanks,
do I need Microsoft Office installed?

**Comment by x97mdr** [comment]
No, you can output Word documents from Pickles without Word installed.  To
read them you need Word installed of course (or a fre alternative that can
read OpenXML documents like LibreOffice or OpenOffice)

On Tue, Jul 17, 2012 at 9:35 AM, Muffon <
reply@reply.github.com

**Comment by Muffon** [comment]
Well, here I get the error:

Pickle-Features : Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.0.5022.0, Culture=neutral, PublicKeyToken=31bf3
856ad364e35' or one of its dependencies. Systém nemůže nalézt uvedený soubor.

but still in vesrion 0.4, 

viz. Issue #97

**Comment by x97mdr** [comment]
Where are you running Pickles from? the NuGet package? or the downloaded
.zip file from Github/ or compiled source?  It should be easy enough to
grab the DocumentFormat.OpenXml assembly from the web and drop it in the
same folder as the Pickles powershell module.

On Wed, Jul 18, 2012 at 3:23 AM, Muffon <
reply@reply.github.com

**Comment by Muffon** [comment]
I am running it from nuget console(downloaded from nuget repo). I cant build from source because of proxy so it is an only option for now :-)

**Comment by x97mdr** [comment]
OK, there may have been a bug in 0.4, can you try upgrading to the latest
version and see if you get the same error, please?

On Wed, Jul 18, 2012 at 6:13 AM, Muffon <
reply@reply.github.com

**Comment by Muffon** [comment]
In version 0.6 I am getting the same error.
