### ISSUE TITLE
Build behind proxy

### ISSUE THREAD

**Issue by Muffon** [x97mdr/pickles#97]
I know, it is more related to nuget than pickles. But you may know how to solve it. When I want to build(in VS2010 or through build.cmd),  I see in the output for example:

```
 [exec]   "D:\Projects\x97mdr-pickles-12736f8\src\Pickles\.nuget\nuget.exe" install "D:\Projects\x97mdr-pickles-12736f8\src\Pickles\Pickles.Example.xUnit\packages.config" -source "" -o "D:\Projects\x97mdr-pickles-12736f8\src\Pickles\packages"
 [exec]   Please provide proxy credentials:
 [exec]   UserName: Password:
```

and build won't wait. It just fails to build. I don't know how to pass the credentials.

**Comment by x97mdr** [comment]
I actually have no internet connection to my workstation at my work so I've
never run across this.  A quick Google search turned up this thread though
... you could try the ideas mentioned here:
http://nuget.codeplex.com/workitem/231

On Wed, Jul 18, 2012 at 3:18 AM, Muffon <
reply@reply.github.com

**Comment by Muffon** [comment]
Adding settings(cant insert here) to system.net in devenv.exe.config  helped when building in Visual Studio and from command line as well. Thank you!
